# SITE CONFIGURATION
baseurl: ""
url: "https://mullaepro.com"

# THEME-SPECIFIC CONFIGURATION
title: Blanc # site's title
description: "A website with error blog posts" # used by search engines
avatar: assets/img/avatar.jpeg # Empty for no avatar in navbar
favicon: assets/favicon.ico # Icon displayed in the tab

# Header and footer text
header_text: Error Blog # Change Blog header text
header_feature_image: assets/img/11111.jpg
header_feature_image_responsive: true
footer_text: >
  1yoouoo.github.io

# Blog
excerpt: true # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png # A bit transparent for color posts.

# Features
# More in the _data folder for share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true # Enable if using math markup
mermaid: default # Enable mermaid-js for diagrams, use theme: base, forest, dark, default, neutral
google_analytics: 
cookie_consent: false # To respect the usage of cookies
color_theme: dark # auto, dark or light

# Comments
comments:
  disqus_shortname: # Your discus shortname for comments
  cusdis_app_id: # Your cusdis data-app-id
  utterances: # Enable by filling below information. For more info, go to https://utteranc.es
    repo: # your public comments repository (e.g. owner/repo)
    issue-term: # Issue term (e.g. "comment" consider issues with this word in the title as comments)

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
sass:
  style: compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude:
  [
    ".jekyll-cache",
    ".jekyll-metadata",
    ".idea",
    "vendor/*",
    "assets/node_modules/*",
  ]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap # If using as a remote_theme in github
